"""empty message

Revision ID: 0b3ac450d762
Revises: c53abf62b0f9
Create Date: 2022-01-05 19:28:58.596593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3ac450d762'
down_revision = 'c53abf62b0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restricted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'restricted')
    # ### end Alembic commands ###
