"""empty message

Revision ID: 787236a797db
Revises: d0752975378f
Create Date: 2022-01-05 16:40:17.193303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787236a797db'
down_revision = 'd0752975378f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('answer_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'answer_time')
    # ### end Alembic commands ###
